export type RuntimeErrorCode =
  | 'VALIDATION_FAILED'
  | 'UNAUTHORIZED'
  | 'RUN_NOT_FOUND'
  | 'RUN_ALREADY_TERMINAL'
  | 'THREAD_NOT_FOUND'
  | 'THREAD_ARCHIVED'
  | 'THREAD_HAS_ACTIVE_RUN'
  | 'THREAD_CONFIG_IMMUTABLE'
  | 'THREAD_CONCURRENCY_CONFLICT'
  | 'RESUME_TARGET_NOT_FOUND'
  | 'RESUME_CAPABILITY_UNVERIFIED'
  | 'RESUME_FAILED'
  | 'CODEX_THREAD_ID_MISSING'
  | 'THREAD_RUN_ORPHANED'
  | 'WORKSPACE_BUSY'
  | 'CODEX_NOT_FOUND'
  | 'CODEX_AUTH_REQUIRED'
  | 'CODEX_HOME_READ_ONLY'
  | 'CODEX_PROFILE_NOT_FOUND'
  | 'CODEX_PROFILE_EXISTS'
  | 'CODEX_PROFILE_INVALID'
  | 'CODEX_CONFIG_WRITE_FAILED'
  | 'CODEX_CONFIG_LOCKED'
  | 'CODEX_CONFIG_INVALID'
  | 'CODEX_SKILL_NOT_FOUND'
  | 'CODEX_SKILL_EXISTS'
  | 'CODEX_SKILL_INVALID'
  | 'CODEX_SKILL_WRITE_FAILED'
  | 'CODEX_SKILL_WRITE_CONFIRMATION_REQUIRED'
  | 'CODEX_INCOMPATIBLE'
  | 'CODEX_UNVERIFIED_WRITE_BLOCKED'
  | 'SPAWN_FAILED'
  | 'CODEX_STREAM_ERROR'
  | 'MCP_COMMAND_FAILED'
  | 'MCP_SERVER_NOT_FOUND'
  | 'MCP_SERVER_EXISTS'
  | 'MCP_SERVER_INVALID'
  | 'MCP_WRITE_CONFIRMATION_REQUIRED'
  | 'SCHEDULE_INVALID'
  | 'SCHEDULE_NOT_FOUND'
  | 'CLEANUP_FAILED'
  | 'INTERNAL_ERROR';

export type ApiError = {
  error: {
    code: RuntimeErrorCode;
    message: string;
    details?: Record<string, unknown>;
  };
};
