import type { CreatorSkillSource } from './types.js';

export const customSkills: CreatorSkillSource[] = [
  {
    id: "beili-sensor-mini-class",
    name: "beili-sensor-mini-class",
    titleZh: "北立传感小课堂",
    tagline: "输入一段文案、Word 或网页，一键生成火柴人风格的传感器科普视频。",
    summary: "北立传感小课堂用于把传感器相关资料转成火柴人风格科普视频，适合产品知识讲解、客户教育和内部培训。",
    category: "video-subtitle",
    subcategory: "科普短片",
    platforms: ["北立专属", "视频"],
    tasks: ["火柴人科普", "文案转视频", "Word 转视频", "网页转视频", "科普短片"],
    businessGoals: ["content-production", "customer-retention"],
    creator: {
      name: "北立传感器",
      avatarUrl: "https://github.com/BeLeadSensor.png",
    },
    github: {
      repo: "BeLeadSensor/sensor-mini-class",
      url: "https://github.com/BeLeadSensor/sensor-mini-class",
      stars: 0,
      forks: 0,
      license: null,
      lastPushedAt: "2026-07-10",
      defaultBranch: "main",
      readmeText:
        "北立传感小课堂可以把一段文案、Word 或网页资料转成火柴人风格的传感器科普视频。\n\n适合场景：\n\n- 传感器概念科普。\n- 产品知识讲解。\n- 销售培训素材。\n- 企业公众号和短视频科普。",
      readmeLanguage: "zh",
    },
    examples: [],
    inputs: ["文案", "Word", "网页链接", "产品资料"],
    outputs: ["火柴人科普视频", "短视频脚本", "字幕", "配音"],
    install: {
      agentInstruction: "让 Clawee 读取输入资料，生成视频结构、分镜、配音字幕和火柴人风格画面方案。",
      humanSteps: ["输入资料", "确认脚本", "生成视频", "检查并发布"],
      command: "git clone https://github.com/BeLeadSensor/sensor-mini-class.git",
      officialDocsUrl: "https://github.com/BeLeadSensor/sensor-mini-class",
    },
    risks: {
      requiresLogin: false,
      requiresApiKey: false,
      externalWrite: false,
      readsLocalFiles: true,
      commercialLicenseReview: false,
      privateDataRisk: true,
      notes: ["输入资料可能包含企业内部信息，生成前需要确认资料可用于视频生产。"],
    },
    listingStatus: "featured",
    relatedSkillIds: ["krillinai-krillinai", "remotion-dev-remotion"],
  },
  {
    id: "beili-product-promo-video",
    name: "beili-product-promo-video",
    titleZh: "产品宣传片",
    tagline: "输入北立传感器产品资料，一键生成产品宣传介绍视频。",
    summary: "产品宣传片用于把传感器产品资料整理成介绍视频，适合官网、展会、销售跟进和客户方案展示。",
    category: "video-subtitle",
    subcategory: "产品宣传片",
    platforms: ["北立专属", "视频"],
    tasks: ["产品宣传片", "产品资料转视频", "销售视频", "产品介绍", "展会素材"],
    businessGoals: ["content-production", "lead-generation", "conversion"],
    creator: {
      name: "北立传感器",
      avatarUrl: "https://github.com/BeLeadSensor.png",
    },
    github: {
      repo: "BeLeadSensor/product-promo-video",
      url: "https://github.com/BeLeadSensor/product-promo-video",
      stars: 0,
      forks: 0,
      license: null,
      lastPushedAt: "2026-07-10",
      defaultBranch: "main",
      readmeText:
        "产品宣传片可以把北立传感器产品资料转成一条产品宣传介绍视频。\n\n适合场景：\n\n- 官网产品介绍。\n- 展会循环播放素材。\n- 销售跟进视频。\n- 客户方案展示。",
      readmeLanguage: "zh",
    },
    examples: [],
    inputs: ["产品资料", "产品图片", "参数说明", "应用场景"],
    outputs: ["产品宣传视频", "产品介绍脚本", "字幕", "配音"],
    install: {
      agentInstruction: "让 Clawee 根据产品资料提炼卖点、生成视频脚本、分镜、字幕和配音方案。",
      humanSteps: ["输入产品资料", "确认卖点", "生成视频", "检查并发布"],
      command: "git clone https://github.com/BeLeadSensor/product-promo-video.git",
      officialDocsUrl: "https://github.com/BeLeadSensor/product-promo-video",
    },
    risks: {
      requiresLogin: false,
      requiresApiKey: false,
      externalWrite: false,
      readsLocalFiles: true,
      commercialLicenseReview: false,
      privateDataRisk: true,
      notes: ["产品资料、客户案例和应用场景在发布前需要做商业信息检查。"],
    },
    listingStatus: "featured",
    relatedSkillIds: ["krillinai-krillinai", "remotion-dev-remotion"],
  },
];
